### PR TITLE
MYM-39-refactoring-custom-respository-delete

### PR DESCRIPTION
**Pull request by enaenen**
closing #30

### CODE REVIEW

**Review by codeyoma — APPROVED** [review]
```
⌒```⌒*. 선물이
 ●   ● : 야~
〃 ∇ 〃 * 예뿐
 ......*" 장미~
--○--`-{@~~♡
```

**Review by lscitl — APPROVED** [review]
LGTM (대충 따봉 이모지)

**Comment by enaenen** [comment]
٩( ᐛ )و

**Pull request merged**
